config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'admin/dashboard'
  get 'admin/classifications'
  get 'admin/statuses'
  get 'admin/properties'
  get 'admin/roles'

  resources :classifications
  resources :statuses
  resources :properties

  resources :roles do
    resources :privileges
    resources :assignments, controller: 'role_assignments'
  end

  resources :documents do
    get :export
    resources :permissions
  end

  resources :blocks do
    collection do
      get :code2html
      get :rst2html
    end
  end

  resources :teams do
    resources :documents, only: [:index]
    member do
      delete :members, action: :remove_member
      post :members, action: :add_member
    end
  end

  root to: 'pages#dashboard'

  # auth
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
    get 'users', to: 'users/registrations#index', as: :users
    get 'users/:id', to: 'users/registrations#show', as: :user
    get 'settings', to: 'users/registrations#edit', as: :settings
    put 'settings', to: 'users/registrations#update'
    delete 'users', to: 'users/registrations#destroy', as: :destroy_user
  end

  resources :users, only: [] do
    resources :documents, only: [:index]
    resources :teams, only: [:index]
  end
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.sticky-top.navbar-dark.bg-primary.py-lg-0

  = link_to root_url, class: 'navbar-brand' do
    = image_tag 'logo-white.svg', width: 25, height: 25, loading: :lazy, alt: 'Doksi home'
  %button.navbar-toggler{ type: 'button',
                          data: { toggle: 'collapse', target: '#navbar' },
                          aria: { controls: 'navbar', expanded: 'false', label: 'Toggle navigation' } }
    %span.navbar-toggler-icon

  .collapse.navbar-collapse#navbar

    %ul.navbar-nav.flex-fill#nav-links
      %li.nav-item
        = navbar_link 'Documents', documents_path, controller: :documents
      %li.nav-item
        = navbar_link 'Teams', teams_path, controller: :teams

      - if user_signed_in? && current_user.admin?
        %li.nav-item
          = navbar_link 'Admin', admin_dashboard_path, controller: :admin

    = form_tag documents_path, method: :get, class: 'form-inline my-2 my-lg-0' do
      .form-group
        = text_field_tag :search, params[:search], placeholder: 'Search', size: 40,
                         class: 'form-control form-control-sm mr-sm-2 bg-primary text-light'

    %ul.navbar-nav#nav-auth
      - if user_signed_in?
        %users-menu#user-menu{ json: current_user.to_json,
                              settings_path: settings_path,
                              profile_path: user_path(current_user),
                              sign_out_path: destroy_user_session_path }

      - else
        %li.nav-item
          = link_to 'Sign in', new_user_session_path, class: 'nav-link'

app/views/layouts/admin.html.haml
- content_for :content do
  %h3.text-center.text-muted.mt-3.text-uppercase.font-weight-bold Admin area
  %nav.nav.justify-content-center.nav-pills.mt-3
    = navbar_link 'Dashboard', admin_dashboard_path, controller: :admin, action: :dashboard
    = navbar_link 'Classifications', admin_classifications_path, controller: :admin, action: :classifications
    = navbar_link 'Statuses', admin_statuses_path, controller: :admin, action: :statuses
    = navbar_link 'Properties', admin_properties_path, controller: :admin, action: :properties
    = navbar_link 'Roles', admin_roles_path, controller: :admin, action: :roles
  .m-5
    = yield

= render template: 'layouts/application'

app/views/layouts/application.html.haml
!!! 5

%html{ lang: 'en' }

  %head

    %title Doksi
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag asset_path('logo-blue-32.png')
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    - if content_for? :head
      = yield :head
    %meta{ charset: 'utf-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no' }

  %body
    .d-flex.flex-column#doksi
      = render 'layouts/navbar'
      = render 'shared/alerts'
      = content_for?(:content) ? yield(:content) : yield

  - if content_for? :script
    = yield :script